name: "Deploy built docs to QuantCDN"

on:
  push:
    branches:
      - develop
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set environment for branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
              echo "QUANT_PROJECT=${{ secrets.QUANT_PROJECT_PRODUCTION }}" >> "$GITHUB_ENV"
              echo "QUANT_CUSTOMER=${{ secrets.QUANT_CUSTOMER_PRODUCTION }}" >> "$GITHUB_ENV"
              echo "QUANT_TOKEN=${{ secrets.QUANT_TOKEN_PRODUCTION }}" >> "$GITHUB_ENV"
          else
              echo "QUANT_PROJECT=${{ secrets.QUANT_PROJECT_EDGE }}" >> "$GITHUB_ENV"
              echo "QUANT_CUSTOMER=${{ secrets.QUANT_CUSTOMER_EDGE }}" >> "$GITHUB_ENV"
              echo "QUANT_TOKEN=${{ secrets.QUANT_TOKEN_EDGE }}" >> "$GITHUB_ENV"
          fi

      - uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build docs
        run: yarn run build

      - name: Show generated outputs
        run: find build

      - name: Cache local revision file
        id: cache-quant-revisions
        uses: actions/cache@v2
        with:
          path: .quant-revision
          key: quant-revision

      - name: Deploy updates to QuantCDN
        uses: quantcdn/deploy-action@v2.0.0
        with:
          customer: "${{ env.QUANT_CUSTOMER }}"
          project: "${{ env.QUANT_PROJECT }}"
          token: "${{ env.QUANT_TOKEN }}"
          dir: build
          chunk-size: 20
          skip-purge: true
          enable-index-html: true
          revision-log: .quant-revision

      - name: Purge the QuantCDN cache
        uses: quantcdn/purge-action@v1.2.0
        with:
          customer: "${{ env.QUANT_CUSTOMER }}"
          project: "${{ env.QUANT_PROJECT }}"
          token: "${{ env.QUANT_TOKEN }}"
          url_pattern: "/*"
